### ISSUE TITLE
UCEProtect is extortionist

### ISSUE THREAD

**Issue by mrcbax** [ilijamt/blacklist-checker#2]
The UCEProtect RBL is a known extortion racket, its lists should not be used.

https://en.wikipedia.org/wiki/Comparison_of_DNS_blacklists#Suspect_RBL_providers

**Comment by ilijamt** [comment]
Removed them

**Comment by kartoffelheinz** [comment]
backscatterer.org also belongs to the same extortion racket and should thus also not used.
