### ISSUE TITLE
Failed to Query

### ISSUE THREAD

**Issue by cepa995** [ilijamt/blacklist-checker#3]
Hi,

I found this project really interesting and I am trying to figure out how to use it, but ever time I do so (even after following your examples) I get following output:
```

./bin/blacklist-checker ip 46.217.104.208 --verbose

Failed to query: read udp 10.0.2.15:56510->8.8.8.8:53: i/o timeout for 46.217.104.208 on spam.spamrats.com with query 208.104.217.46.spam.spamrats.com.
Failed to query: read udp 10.0.2.15:58112->8.8.8.8:53: i/o timeout for 46.217.104.208 on noptr.spamrats.com with query 208.104.217.46.noptr.spamrats.com.
Failed to query: read udp 10.0.2.15:51462->8.8.8.8:53: i/o timeout for 46.217.104.208 on dyna.spamrats.com with query 208.104.217.46.dyna.spamrats.com.
Checking 208.104.217.46.spam.spamrats.com.
Checking 208.104.217.46.dyna.spamrats.com.
Checking 208.104.217.46.noptr.spamrats.com.
```

What am I doing wrong? Is server name the issue, or?

**Comment by ilijamt** [comment]
Hi, @cepa995 

Probably spam DNS sites do not exist anymore. 
The easiest way is to remove the items from https://github.com/ilijamt/blacklist-checker/blob/master/blacklists.go, and recompile the application. Probably a lot of them are dead now, initially I took the list off https://mxtoolbox.com/problem/blacklist/, but it's probably too much. 

Just remove all you don't need to and leave the ones you want to and recompile the application, and you will not have a problem.

**Comment by ilijamt** [comment]
I've refactored the application, it's been a long time coming.
You can specify your own blacklist now from the command line. 

Please check the latest release 
https://github.com/ilijamt/blacklist-checker/releases/latest
